stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  tags:
    - chatops
    - shell
  script:
    - export JAVA_HOME=/home/swfarmer/.local/java/jdk-11.0.21+9
    - export PATH="$JAVA_HOME/bin:/home/swfarmer/.local/maven/apache-maven-3.9.6/bin:$PATH"
    - mvn clean package -DskipTests -B
  artifacts:
    paths:
      - target/*.hpi
    expire_in: 30 days
  only:
    - tags
