services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cerberus-jenkins-test
    hostname: cerberus-jenkins-test
    ports:
      - "8888:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    tty: true

volumes:
  jenkins_home:
